import { runAiPrompt } from '../../aiClient';
import { buildIndividualEvaluatorPrompt } from '../prompts/individualEvaluatorPrompt';
import { buildGlobalEvaluatorPrompt } from '../prompts/globalEvaluatorPrompt';
import { extractJsonObject } from '../utils';

export interface IndividualEvaluationResult {
  approved: boolean;
  feedback?: string;
}

export interface GlobalEvaluationResult {
  approved: boolean;
  globalIssues?: string;
  exerciseModifications?: {
    exerciseIndex: number;
    feedback: string;
  }[];
}

export class EvaluatorAgent {
  /**
   * Evaluates a single exercise generated by the AC.
   */
  async evaluateExercise(
    plan: { type: string; objective: string; instruction: string; description: string },
    generatedExercise: any,
    childProfile: string,
    language: 'es' | 'val' | 'en'
  ): Promise<IndividualEvaluationResult> {
    try {
      const prompt = buildIndividualEvaluatorPrompt(plan, generatedExercise, childProfile, language);
      const responseRaw = await runAiPrompt(prompt);
      const parsed = JSON.parse(extractJsonObject(responseRaw)) as IndividualEvaluationResult;
      return {
        approved: !!parsed.approved,
        feedback: parsed.feedback || undefined,
      };
    } catch (error) {
      console.warn("Error al evaluar el ejercicio de forma individual. Aprobando por defecto:", error);
      // En caso de error del LLM o parseado, aprobamos para evitar bloqueos
      return { approved: true };
    }
  }

  /**
   * Evaluates the entire assembled worksheet.
   */
  async evaluateWorksheet(
    childProfile: string,
    topic: string,
    goal: string,
    worksheetContent: any,
    language: 'es' | 'val' | 'en'
  ): Promise<GlobalEvaluationResult> {
    try {
      const prompt = buildGlobalEvaluatorPrompt(childProfile, topic, goal, worksheetContent, language);
      const responseRaw = await runAiPrompt(prompt);
      const parsed = JSON.parse(extractJsonObject(responseRaw)) as GlobalEvaluationResult;
      return {
        approved: !!parsed.approved,
        globalIssues: parsed.globalIssues || undefined,
        exerciseModifications: parsed.exerciseModifications || [],
      };
    } catch (error) {
      console.warn("Error al evaluar la ficha de forma global. Aprobando por defecto:", error);
      // En caso de error, aprobamos por defecto
      return { approved: true };
    }
  }
}
