import { compact } from './shared';

export const buildIndividualEvaluatorPrompt = (
  plan: { type: string; objective: string; instruction: string; description: string },
  generatedExercise: any,
  childProfile: string,
  language: 'es' | 'val' | 'en'
): string => {
  const languageNames = {
    es: 'Castilian Spanish (es)',
    val: 'Valencian/Catalan (val)',
    en: 'English (en)',
  };
  const targetLang = languageNames[language] || languageNames.es;

  return compact(
    `You are the Pedagogical Evaluator Agent (PEA) for Pictalia.
Your role is to review a single educational exercise generated by the Exercise Constructor Agent (AC) against the student's profile and the pedagogical plan.`,
    `STUDENT PROFILE:
${childProfile}`,
    `PEDAGOGICAL PLAN FOR THIS EXERCISE:
- Exercise Type: ${plan.type}
- Objective: ${plan.objective}
- Instruction: ${plan.instruction}
- Detailed Content Description: ${plan.description}`,
    `GENERATED EXERCISE (JSON):
${JSON.stringify(generatedExercise, null, 2)}`,
    `EVALUATION CRITERIA:
1. **Conceptual Correctness**: Check if the exercise is complete, logical, and has no formatting or semantic errors.
2. **Pedagogical Alignment**: Verify if it matches the plan's description and objective (e.g. if the plan asks for matching words to numbers, does it do exactly that?).
3. **Student Suitability**: Ensure that the content is appropriate for the student's profile (e.g., if the student has high support needs, the text is simple, the exercise instructions are concise, etc.).
4. **Language**: Check if all student/teacher-facing texts are written in ${targetLang}.
5. **Layout & Schema**: Check if key fields like "exerciseType" match the requested type.
6. **Strict Pictogram Naming**: Every search term ("searchTerm") and visible text content ("content") in any pictogram array or item (e.g., in instruction.pictograms or exercise items) MUST be a SINGLE word (e.g., "perro", "rojo").
   - Reject and demand correction if you see multi-word phrases (e.g., "perro grande", "la casa", "comer manzana").
   - CRITICAL: Reject and demand correction if any "searchTerm" contains underscores ("_"), hyphens ("-"), or suffixes like "_pictograma", "_picto", "_image", "_dibujo" (e.g. "mango_pictograma" is strictly invalid, it must be simply "mango"). Search terms must be clean dictionary words without qualifying suffixes.`,
    `OUTPUT FORMAT:
You must return ONLY a valid JSON object matching this schema:
{
  "approved": boolean,
  "feedback": "If approved is false, write a detailed explanation of what is wrong and how to fix it in English. If approved is true, omit this field or leave it empty."
}`,
    `JSON ONLY. Respect Markdown JSON formatting.`
  );
};
